# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-16 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(verbose_name='链接')),
                ('status', models.SmallIntegerField(choices=[(0, '未使用'), (1, '正在使用'), (2, '已删除')], verbose_name='状态')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('l_language', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='programs.Language', verbose_name='编程语言')),
            ],
        ),
    ]
