# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-17 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': '链接'},
        ),
        migrations.AddField(
            model_name='link',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'URL路由'), (1, '绝对路径')], default=0, verbose_name='链接类型'),
        ),
    ]
