# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-15 10:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0003_auto_20190515_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_link', models.CharField(max_length=255, verbose_name='工具连接')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('add_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建管理员')),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tools.Type', verbose_name='类别')),
            ],
            options={
                'verbose_name': '工具链接',
            },
        ),
    ]
