# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-16 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '未使用'), (1, '已使用'), (2, '已删除')], verbose_name='类别状态'),
        ),
    ]
